### ISSUE TITLE
Support SonarQube > 8.0

### ISSUE THREAD

**Issue by barfuin** [checkstyle-addons/checkstyle-addons#3]
The Checkstyle Addons plugin for SonarQube currently supports only SonarQube 7.9 and older. This is currently the LTS version, so we are good atm.

However, it is already clear that SonarQube 8.0 (8.3 actually), will have breaking API changes, so that the plugin code will have to be adjusted. This issue is for getting Checkstyle Addons to run on the newest SonarQube (8.4+).

**Comment by tsjensen** [comment]
Thanks for letting me know. If you can contribute this, that would be great!

**Comment by tsjensen** [comment]
Added a notice about this to the website: https://checkstyle-addons.thomasjensen.com/run.html#run-sonarqube

**Comment by tsjensen** [comment]
The latest SonarQube, including v8.0, is now supported with Checkstyle Addons [v7.0.0](https://github.com/checkstyle-addons/checkstyle-addons/releases/tag/v7.0.0).
